PP2_MOD_DIR = $(KDIR)/drivers/net/ethernet/marvell/mvpp2x

obj-m := pkt-echo.o

pkt-echo-y += ks_pkt_echo.o

ccflags-y := -I$(src)/../../../../src/include
ccflags-y += -I$(src)/../../../../src
ccflags-y += -I$(src)/../../../../apps/include
ccflags-y += -I${PP2_MOD_DIR}
